[workspace]
members = ["rumina-lib", "ruminac", "rmvm"]
resolver = "2"

[workspace.package]
version = "1.1.1"
edition = "2024"
license = "LGPL-2.1"

[workspace.dependencies]
num = "^0.4"
rand = "^0.9"
chrono = "^0.4"
lazy_static = "^1.4"
mathcore = "^0.3.1"
