[package]
name = "rmpack"
version = "1.0.0"
edition = "2024"
description = "Rumina Packager"
license = "LGPL-2.1"

[[bin]]
name = "rmpack"
path = "src/main.rs"

[dependencies]
rumina = { path = ".." }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ctrlc = "^3"
